import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { BreadcrumbModule } from 'angular-crumbs';
import { AdminRoutes } from './admin.routing';
import { DirectivesModule } from 'src/app/shared/directives/directive.module';

// Admin Components
import { BreadcrumbsComponent } from 'src/app/components/breadcrumb/breadcrumb.component';
import { PaginationComponent } from 'src/app/components/pagination/pagination.component';
import {
	// Home
	HomeComponent,
	// Profile
	ProfileDetailComponent,
	UpdatePhotoComponent,
	UpdateInfoComponent,
	UpdatePasswordComponent,
	// Settings
	SettingsComponent,
	// Message
	MessagesComponent,
	// Notification
	NotificationsComponent,
	// Page Not Found
	PageNotFoundComponent,
	// HTML
	HtmlCssComponent,
	HtmlComponent,
	// CSS
	CssComponent,
	// Colors
	ColorsComponent,
	// Bootstrap
	BootstrapComponent,
	BsLayoutComponent,
	BsOverviewComponent,
	BsGridComponent,
	BsUtilitiesForLayoutComponent,
	BsContentComponent,
	BsRebootComponent,
	BsTypographyComponent,
	BsCodeComponent,
	BsImagesComponent,
	BsTablesComponent,
	BsFiguresComponent,
	BsComponentsComponent,
	BsAlertsComponent,
	BsBadgeComponent,
	BsBreadcrumbComponent,
	BsButtonsComponent,
	BsButtonGroupComponent,
	BsCardComponent,
	BsCarouselComponent,
	BsCollapseComponent,
	BsDropdownsComponent,
	BsFormsComponent,
	BsInputGroupComponent,
	BsJumbotronComponent,
	BsListGroupComponent,
	BsMediaObjectComponent,
	BsModalComponent,
	BsNavsComponent,
	BsNavbarComponent,
	BsPaginationComponent,
	BsPopoversComponent,
	BsProgressComponent,
	BsScrollspyComponent,
	BsSpinnersComponent,
	BsToastsComponent,
	BsTooltipsComponent,
	BsUtilitiesComponent,
	BsBordersComponent,
	BsClearfixComponent,
	BsCloseIconComponent,
	BsColorsComponent,
	BsDisplayComponent,
	BsEmbedComponent,
	BsFlexComponent,
	BsFloatComponent,
	BsImageReplacementComponent,
	BsOverflowComponent,
	BsPositionComponent,
	BsScreenReadersComponent,
	BsShadowsComponent,
	BsSizingComponent,
	BsSpacingComponent,
	BsStretchedLinkComponent,
	BsTextComponent,
	BsVerticalAlignComponent,
	BsVisibilityComponent,
	// Icons
	IconsComponent,
	FontAwesomeComponent,
	ThemifyComponent,
	// Graphics
	GraphicsComponent,
	// Javascript
	JscriptComponent,
	JavascriptComponent,
	JqueryComponent,
	JsonComponent,
	AjaxComponent,
	// Server Side
	ServerSideComponent,
	SqlComponent,
	PhpComponent,
	PythonComponent,
	JavaComponent,
	AspComponent,
	NodejsComponent,
	RaspberrypiComponent,
	// XML
	XmlsComponent,
	XmlComponent,
	XmlAjaxComponent,
	XmlDomComponent,
	XmlDtdComponent,
	XmlSchemaComponent,
	XsltComponent,
	XpathComponent,
	XqueryComponent,
} from 'src/app/pages/admin';

@NgModule({
	imports: [
		CommonModule,
		FormsModule,
		ReactiveFormsModule,
		RouterModule.forChild(AdminRoutes),
		BreadcrumbModule,
		DirectivesModule,
	],
	declarations: [
		BreadcrumbsComponent,
		PaginationComponent,
		HomeComponent,
		ProfileDetailComponent,
		UpdatePhotoComponent,
		UpdateInfoComponent,
		UpdatePasswordComponent,
		SettingsComponent,
		MessagesComponent,
		NotificationsComponent,
		PageNotFoundComponent,
		// HTML CSS
		HtmlCssComponent,
		HtmlComponent,
		CssComponent,
		ColorsComponent,
		// Bootstrap
		BootstrapComponent,
		BsLayoutComponent,
		BsOverviewComponent,
		BsGridComponent,
		BsUtilitiesForLayoutComponent,
		BsContentComponent,
		BsRebootComponent,
		BsTypographyComponent,
		BsCodeComponent,
		BsImagesComponent,
		BsTablesComponent,
		BsFiguresComponent,
		BsComponentsComponent,
		BsAlertsComponent,
		BsBadgeComponent,
		BsBreadcrumbComponent,
		BsButtonsComponent,
		BsButtonGroupComponent,
		BsCardComponent,
		BsCarouselComponent,
		BsCollapseComponent,
		BsDropdownsComponent,
		BsFormsComponent,
		BsInputGroupComponent,
		BsJumbotronComponent,
		BsListGroupComponent,
		BsMediaObjectComponent,
		BsModalComponent,
		BsNavsComponent,
		BsNavbarComponent,
		BsPaginationComponent,
		BsPopoversComponent,
		BsProgressComponent,
		BsScrollspyComponent,
		BsSpinnersComponent,
		BsToastsComponent,
		BsTooltipsComponent,
		BsUtilitiesComponent,
		BsBordersComponent,
		BsClearfixComponent,
		BsCloseIconComponent,
		BsColorsComponent,
		BsDisplayComponent,
		BsEmbedComponent,
		BsFlexComponent,
		BsFloatComponent,
		BsImageReplacementComponent,
		BsOverflowComponent,
		BsPositionComponent,
		BsScreenReadersComponent,
		BsShadowsComponent,
		BsSizingComponent,
		BsSpacingComponent,
		BsStretchedLinkComponent,
		BsTextComponent,
		BsVerticalAlignComponent,
		BsVisibilityComponent,
		// Icons
		IconsComponent,
		FontAwesomeComponent,
		ThemifyComponent,
		GraphicsComponent,
		// Javascript
		JscriptComponent,
		JavascriptComponent,
		JqueryComponent,
		JsonComponent,
		AjaxComponent,
		// Server Side
		ServerSideComponent,
		SqlComponent,
		PhpComponent,
		PythonComponent,
		JavaComponent,
		AspComponent,
		NodejsComponent,
		RaspberrypiComponent,
		// XML
		XmlsComponent,
		XmlComponent,
		XmlAjaxComponent,
		XmlDomComponent,
		XmlDtdComponent,
		XmlSchemaComponent,
		XsltComponent,
		XpathComponent,
		XqueryComponent,
	],
})
export class AdminLayoutModule {}
